# Generated by Django 4.0.5 on 2022-06-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.TextField(blank=True)),
                ('act_type_1', models.CharField(max_length=255)),
                ('act_type_2', models.CharField(blank=True, max_length=255, null=True)),
                ('act_name', models.CharField(max_length=255)),
                ('act_note', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
