# Generated by Django 4.0.5 on 2022-07-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act_record',
            name='act_dtl',
        ),
        migrations.RemoveField(
            model_name='act_record',
            name='act_note',
        ),
        migrations.RemoveField(
            model_name='act_record',
            name='dt_date',
        ),
        migrations.RemoveField(
            model_name='calories_record',
            name='cal_goal',
        ),
        migrations.AddField(
            model_name='calories_record',
            name='cal_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Detail_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtl_detail', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('dtl_note', models.TextField(blank=True, default='', null=True)),
                ('tm_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.time_record')),
            ],
        ),
    ]
