# Generated by Django 4.0.5 on 2022-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories_record',
            name='cal_deficit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calories_record',
            name='cal_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calories_record',
            name='cal_morning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calories_record',
            name='cal_night',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calories_record',
            name='cal_noon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
